### ISSUE TITLE
Merge fractal-server and slurm-master Dockerfiles, in `advanced`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-containers#7]
Start with current slurm-master, and add all the current fractal-server directives.

**Comment by tcompa** [comment]
To do: test (by hand or with a script) that you can submit a job for execution, via `sbatch`.

**Comment by aangelone2** [comment]
Solved in `1124125`

**Comment by aangelone2** [comment]
Solved in `1124125`

**Comment by tcompa** [comment]
Closing for now, as we are taking a different direction with this repo for the moment (ref #19).
